### ISSUE TITLE
Dates in location info modals not working properly :heart:

### ISSUE THREAD

**Issue by mhxu** [hansonw/consilium#100]
Its currently just a number field starting at 0.  At least change it so -1 gives AD dates.
(More specifically, the 'year' fields in all the modals. Should probably be a dropdown like most other sites or something)

**Comment by sebslaman** [comment]
they give negative numbers and 'dont work' in that sense 

The 'year built' in 'risk infos' in 'location info' should be one of these forms.  :heart:
