### ISSUE TITLE
Sections should be able to default to expanded

### ISSUE THREAD

**Issue by DouglasSherk** [hansonw/consilium#111]
Currently, sections can default to expanded, but we had to add an ugly hack that keeps checking the page until it's loaded and then expands it. In the future, we should just lay out sections as being already open and let the rendering engine take care of it.

**Comment by hansonw** [comment]
It's pretty much fixed. It's not quite as ideal as being able to have it default to open without any JS, but the old 'check page until loaded' hack is gone.
