### ISSUE TITLE
The color of the link doesnt change after you click on the client name in the recent client history.

### ISSUE THREAD

**Issue by mhxu** [hansonw/consilium#135]
Hi!

**Comment by DouglasSherk** [comment]
um. hi? how's it going? :p

**Comment by mhxu** [comment]
Going fine.  We saw Eric at the Velocity venture fund event today.

**Comment by DouglasSherk** [comment]
On a scale of (a lot)-(a lot), how much do you miss us?

**Comment by mhxu** [comment]
A lot.  Life is so much different without you.

**Comment by DouglasSherk** [comment]
:heart:

**Comment by mhxu** [comment]
:heart:

**Comment by DouglasSherk** [comment]
This is a result of using the "pretty" class on these links. WONTFIX
