### ISSUE TITLE
Toolbar (Save/Done) button on Create Client form alignment is off

### ISSUE THREAD

**Issue by DouglasSherk** [hansonw/consilium#49]
It's actually the inner content that is now aligned wrong, but it looks at a glance like it's the toolbar that's wrong. See attached image.
![screen shot 2013-07-10 at 2 48 35 pm](https://f.cloud.github.com/assets/1310914/777017/75dee2e6-e991-11e2-8df0-d55c1aec5595.png)

**Comment by mhxu** [comment]
Could you explain what is wrong here?  I dont see anything wrong.

**Comment by DouglasSherk** [comment]
The right edge of the input fields and the right edge of the "Done" button should line up horizontally.
