### ISSUE TITLE
Use new template for submission

### ISSUE THREAD

**Issue by DouglasSherk** [hansonw/consilium#76]
Marc has given us a new template to use. He has also promised to annotate it so we can understand it better. We should use this instead of the survey form for generating submissions.

**Comment by hansonw** [comment]
subissues:

claims info: split into property and automobile
previous policy info: multiple previous policies?
liability info: 'exposure/receipts by operation or product type' what is this?
liquor liability section needed?
statement of values: what is this?

risk info: electrical - size of service
heating + fuel type should be by area

fire extinguisher inspected date/who
crime protection: describe signage, fencing, cameras, alarm company, security guards

seems like there are standard umbrella + machinery breakdown coverages

annual loss control survey
