### ISSUE TITLE
UX meeting notes

### ISSUE THREAD

**Issue by hansonw** [hansonw/consilium#85]
- Remove link tag from Consilium "logo"
- Sort client list by updatedat by default.
- Make back button close modal instead of navigating back.
- Prompt to save when closing modals with partial information.
- In View Client History, breadcrumb should link back to View Client.
- Add autosave option; use save button only when it's disabled
- Show validation errors immediately (ie on blur)
- Company, name -> Company name, contact name
- Date sorting is wrong, also unify date formatting to Month, dd yyyy
- Bold only the sorted-by field.
- Add tutorial for menu button
- Clients / Brokers buttons on home page.

Ask Marc:
- Ask about cancel when editing client
- Ask about toggle for submission/proposal in generate document

**Comment by mhxu** [comment]
For the date formatting, is this format ok? July 17, 2013 10:55 AM

**Comment by DouglasSherk** [comment]
Yes. Will it write "August" or "Aug"? I would prefer shorter months.

**Comment by mhxu** [comment]
I think it write the entire month.  So should I change it to write Jul?

**Comment by DouglasSherk** [comment]
Please. There should be a token for that.

**Comment by hansonw** [comment]
See #68 for other UX-related issues
